// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"chainsawman/file/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: uploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/fetch/:id",
				Handler: fetchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/file"),
	)
}
