// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"chainsawman/file/cmd/rpc/internal/logic"
	"chainsawman/file/cmd/rpc/internal/svc"
	rpc2 "chainsawman/file/cmd/rpc/types/rpc"
	"context"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	rpc2.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) FetchFile(ctx context.Context, in *rpc2.IDReq) (*rpc2.FileReply, error) {
	l := logic.NewFetchFileLogic(ctx, s.svcCtx)
	return l.FetchFile(in)
}
