// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"chainsawman/file/cmd/rpc/internal/logic"
	"chainsawman/file/cmd/rpc/internal/svc"
	"chainsawman/file/cmd/rpc/types/rpc/file"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) FetchFile(ctx context.Context, in *file.IDReq) (*file.FileReply, error) {
	l := logic.NewFetchFileLogic(ctx, s.svcCtx)
	return l.FetchFile(in)
}

func (s *FileServer) UploadFile(ctx context.Context, in *file.FileUploadReq) (*file.FileIDReply, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
