// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/home/approdite/GolandProjects/chainsawman/front/src/models/graph';

export const models = {
model_1: { namespace: 'graph', model: model_1 },
} as const
