// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package fileclient

import (
	"context"

	"chainsawman/file/cmd/rpc/types/rpc/file"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FileIDReply   = file.FileIDReply
	FileReply     = file.FileReply
	FileUploadReq = file.FileUploadReq
	IDReq         = file.IDReq

	File interface {
		FetchFile(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*FileReply, error)
		UploadFile(ctx context.Context, in *FileUploadReq, opts ...grpc.CallOption) (*FileIDReply, error)
	}

	defaultFile struct {
		cli zrpc.Client
	}
)

func NewFile(cli zrpc.Client) File {
	return &defaultFile{
		cli: cli,
	}
}

func (m *defaultFile) FetchFile(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*FileReply, error) {
	client := file.NewFileClient(m.cli.Conn())
	return client.FetchFile(ctx, in, opts...)
}

func (m *defaultFile) UploadFile(ctx context.Context, in *FileUploadReq, opts ...grpc.CallOption) (*FileIDReply, error) {
	client := file.NewFileClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}
