// Code generated by goctl. DO NOT EDIT.
package types

type Graph struct {
	Name  string `json:"name"`
	Desc  string `json:"desc"`
	Nodes int64  `json:"nodes"`
	Edges int64  `json:"edges"`
}

type Node struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type Edge struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

type SearchAllGraphReply struct {
	Base   *BaseReply `json:"base"`
	Graphs []*Graph   `json:"graphs"`
}

type SearchGraphReply struct {
	Base  *BaseReply `json:"base"`
	Graph *Graph     `json:"graph"`
}

type SearchGraphDetailReply struct {
	Base  *BaseReply `json:"base"`
	Nodes []*Node    `json:"nodes"`
	Edges []*Edge    `json:"edges"`
}

type BaseReply struct {
	Status int64             `json:"status"`
	Msg    string            `json:"msg"`
	Extra  map[string]string `json:"extra"`
}

type SearchRequest struct {
	Graph string `path:"graph"`
}
