// Code generated by goctl. DO NOT EDIT.
package types

type Graph struct {
	Name  string `json:"name"`
	Desc  string `json:"desc"`
	Nodes int64  `json:"nodes"`
	Edges int64  `json:"edges"`
}

type Node struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
	Deg  int64  `json:"deg"`
}

type Edge struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

type BaseReply struct {
	Status     int64             `json:"status"`
	Msg        string            `json:"msg"`
	TaskID     int64             `json:"taskId"`
	TaskStatus int64             `json:"taskStatus"`
	Extra      map[string]string `json:"extra"`
}

type SearchAllGraphReply struct {
	Base   *BaseReply `json:"base"`
	Graphs []*Graph   `json:"graphs"`
}

type SearchGraphReply struct {
	Base  *BaseReply `json:"base"`
	Graph *Graph     `json:"graph"`
}

type SearchNodeReply struct {
	Base  *BaseReply `json:"base"`
	Info  *Node      `json:"node"`
	Nodes []*Node    `json:"nodes"`
	Edges []*Edge    `json:"edges"`
}

type SearchGraphDetailReply struct {
	Base  *BaseReply `json:"base"`
	Nodes []*Node    `json:"nodes"`
	Edges []*Edge    `json:"edges"`
}

type SearchRequest struct {
	TaskID int64  `json:"taskId"`
	Graph  string `json:"graph"`
	Min    int64  `json:"min"`
}

type SearchNodeRequest struct {
	TaskID   int64  `json:"taskId"`
	Graph    string `json:"graph"`
	Node     string `json:"node"`
	Distance int64  `json:"distance"`
	Min      int64  `json:"min"`
}

type DropRequest struct {
	Graph string `json:"graph"`
}

type UploadRequest struct {
	TaskID int64  `json:"taskId"`
	Graph  string `json:"graph"`
	NodeID string `json:"nodeId"`
	EdgeID string `json:"edgeId"`
}
