# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo
  namespace: default
spec:
  selector:
    matchLabels:
      app: algo
  template:
    metadata:
      labels:
        app: algo
    spec:
      containers:
        - image: applerodite/chs-algo:latest
          imagePullPolicy: Always
          name: algo
          ports:
            - containerPort: 8081
          env:
            - name: CHS_ENV
              value: "pre"
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: algo-svc
  namespace: default
spec:
  selector:
    app: algo
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081