# Nginx Proxy
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: default
  labels:
    app: front
data:
  graph.conf: |-
    upstream graph {
      server graph-svc:8888;
    }
    
    upstream sca {
      server sca-svc:8082;
    }
    
    upstream minio {
      server minio-svc:9000;
    }
    
    # Allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # Disable buffering
    proxy_buffering off;
    proxy_request_buffering off;
    
    server {
      listen       8000;
      server_name  localhost;
      ignore_invalid_headers off;
      client_max_body_size 0;
      proxy_buffering off;
      proxy_request_buffering off;
    
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    
      location ^~ /api/graph {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Nginx-Proxy true;
        proxy_pass http://graph;
      }
    
      location ^~ /api/util {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Nginx-Proxy true;
        proxy_pass http://sca;
        rewrite "^/api/util/(.*)$" /$1 break;
      }
    
      location ^~ /source {
        proxy_set_header Host minio-svc:9000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
  
        proxy_connect_timeout 300;
        # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
  
        proxy_pass http://minio;
      }
  
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: default
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: applerodite/chs-front:latest
          imagePullPolicy: IfNotPresent
          name: front
          ports:
            - containerPort: 8000
          env:
            - name: CHS_ENV
              value: "pre"
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: graph.conf
      volumes:
        - name: config
          configMap:
            name: front-config
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: default
spec:
  selector:
    app: front
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30123