# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  namespace: default
spec:
  selector:
    matchLabels:
      app: graph
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - image: applerodite/chs-graph:latest
          imagePullPolicy: Always
          name: graph
          ports:
            - containerPort: 8888
          env:
            - name: CHS_ENV
              value: "pre"
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: graph-svc
  namespace: default
spec:
  selector:
    app: graph
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888