# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - image: applerodite/chs-task:latest
          imagePullPolicy: Always
          name: task
          env:
            - name: CHS_ENV
              value: "pre"
      serviceAccountName: find-endpoints