// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"chainsawman/graph/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/graph/getAll",
				Handler: getAllGraphHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/graph/get/:graph",
				Handler: getGraphHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/node/get",
				Handler: getNodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/graph/drop",
				Handler: dropGraphHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/graph/upload",
				Handler: uploadHandler(serverCtx),
			},
		},
	)
}
