// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlgo = "algos"

// Algo mapped from table <algos>
type Algo struct {
	ID        int64         `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name      string        `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc      string        `gorm:"column:desc;type:text" json:"desc"`
	Type      int64         `gorm:"column:type;type:int;not null" json:"type"`
	JarPath   string        `gorm:"column:jarPath;type:varchar(255)" json:"jarPath"`
	MainClass string        `gorm:"column:mainClass;type:varchar(255)" json:"mainClass"`
	IsCustom  int64         `gorm:"column:isCustom;type:tinyint" json:"isCustom"`
	Params    []*AlgosParam `gorm:"foreignKey:algoID" json:"params"`
}

// TableName Algo's table name
func (*Algo) TableName() string {
	return TableNameAlgo
}
