// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlgo = "algo"

// Algo mapped from table <algo>
type Algo struct {
	ID        int64        `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name      string       `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Detail    string       `gorm:"column:detail;type:text" json:"detail"`
	JarPath   string       `gorm:"column:jarPath;type:varchar(255)" json:"jarPath"`
	MainClass string       `gorm:"column:mainClass;type:varchar(255)" json:"mainClass"`
	Tag       string       `gorm:"column:tag;type:varchar(255)" json:"tag"`
	GroupID   int64        `gorm:"column:groupId;type:int;default:1;comment:约束算法应用于某个策略组的图谱，此外：\n1......应用于全部策略组" json:"groupId"`
	Params    []*AlgoParam `gorm:"foreignKey:algoID" json:"params"`
}

// TableName Algo's table name
func (*Algo) TableName() string {
	return TableNameAlgo
}
