// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlgoParam = "algoParam"

// AlgoParam mapped from table <algoParam>
type AlgoParam struct {
	ID      int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AlgoID  int64  `gorm:"column:algoID;type:int;not null" json:"algoID"`
	Name    string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc    string `gorm:"column:desc;type:varchar(255)" json:"desc"`
	Type    int64  `gorm:"column:type;type:int;not null" json:"type"`
	Default string `gorm:"column:default;type:varchar(255)" json:"default"`
	Max     string `gorm:"column:max;type:varchar(255)" json:"max"`
	Min     string `gorm:"column:min;type:varchar(255)" json:"min"`
}

// TableName AlgoParam's table name
func (*AlgoParam) TableName() string {
	return TableNameAlgoParam
}
