// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEdgesAttr = "edges_attr"

// EdgesAttr mapped from table <edges_attr>
type EdgesAttr struct {
	ID      int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	EdgeID  int64  `gorm:"column:edgeID;type:int;not null" json:"edgeID"`
	Name    string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc    string `gorm:"column:desc;type:text" json:"desc"`
	Type    int64  `gorm:"column:type;type:int;not null" json:"type"`
	Primary int64  `gorm:"column:primary;type:tinyint(1);not null" json:"primary"`
}

// TableName EdgesAttr's table name
func (*EdgesAttr) TableName() string {
	return TableNameEdgesAttr
}
