// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEdge = "edge"

// Edge mapped from table <edge>
type Edge struct {
	ID      int64       `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	GroupID int64       `gorm:"column:groupID;type:int;not null" json:"groupID"`
	Name    string      `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc    string      `gorm:"column:desc;type:text" json:"desc"`
	Direct  int64       `gorm:"column:direct;type:tinyint(1);not null;default:1" json:"direct"`
	Display string      `gorm:"column:display;type:varchar(255);default:real" json:"display"`
	Primary string      `gorm:"column:primary;type:varchar(255)" json:"primary"`
	Attrs   []*EdgeAttr `gorm:"foreignKey:edgeID" json:"attrs"`
}

// TableName Edge's table name
func (*Edge) TableName() string {
	return TableNameEdge
}
