// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNodesAttr = "nodes_attr"

// NodesAttr mapped from table <nodes_attr>
type NodesAttr struct {
	ID      int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	NodeID  int64  `gorm:"column:nodeID;type:int;not null" json:"nodeID"`
	Name    string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc    string `gorm:"column:desc;type:text" json:"desc"`
	Type    int64  `gorm:"column:type;type:int;not null" json:"type"`
	Primary int64  `gorm:"column:primary;type:tinyint(1);not null" json:"primary"`
}

// TableName NodesAttr's table name
func (*NodesAttr) TableName() string {
	return TableNameNodesAttr
}
