// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNodeAttr = "nodeAttr"

// NodeAttr mapped from table <nodeAttr>
type NodeAttr struct {
	ID     int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	NodeID int64  `gorm:"column:nodeID;type:int;not null" json:"nodeID"`
	Name   string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc   string `gorm:"column:desc;type:text" json:"desc"`
	Type   int64  `gorm:"column:type;type:int;not null" json:"type"`
}

// TableName NodeAttr's table name
func (*NodeAttr) TableName() string {
	return TableNameNodeAttr
}
