// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"chainsawman/file/rpc/internal/logic"
	"chainsawman/file/rpc/internal/svc"
	"chainsawman/file/rpc/types/rpc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) FetchFile(ctx context.Context, in *rpc.IDReq) (*rpc.FileReply, error) {
	l := logic.NewFetchFileLogic(ctx, s.svcCtx)
	return l.FetchFile(in)
}
