// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEdgeAttr = "edgeAttr"

// EdgeAttr mapped from table <edgeAttr>
type EdgeAttr struct {
	ID     int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	EdgeID int64  `gorm:"column:edgeID;type:int;not null" json:"edgeID"`
	Name   string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc   string `gorm:"column:desc;type:text" json:"desc"`
	Type   int64  `gorm:"column:type;type:int;not null" json:"type"`
}

// TableName EdgeAttr's table name
func (*EdgeAttr) TableName() string {
	return TableNameEdgeAttr
}
