// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExec = "exec"

// Exec mapped from table <exec>
type Exec struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Status     int64     `gorm:"column:status;type:int" json:"status"`
	Params     string    `gorm:"column:params;type:varchar(1024)" json:"params"`
	AlgoID     int64     `gorm:"column:algoID;type:int;not null" json:"algoID"`
	GraphID    int64     `gorm:"column:graphID;type:int;not null" json:"graphID"`
	Output     string    `gorm:"column:output;type:varchar(255)" json:"output"`
	AppID      string    `gorm:"column:appID;type:varchar(255);not null" json:"appID"`
	UpdateTime time.Time `gorm:"column:updateTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updateTime"`
	CreateTime time.Time `gorm:"column:createTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createTime"`
}

// TableName Exec's table name
func (*Exec) TableName() string {
	return TableNameExec
}
