// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNode = "node"

// Node mapped from table <node>
type Node struct {
	ID      int64       `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	GroupID int64       `gorm:"column:groupID;type:int;not null" json:"groupID"`
	Name    string      `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc    string      `gorm:"column:desc;type:text" json:"desc"`
	Display string      `gorm:"column:display;type:varchar(255);default:color" json:"display"`
	Primary string      `gorm:"column:primary;type:varchar(255)" json:"primary"`
	Attrs   []*NodeAttr `gorm:"foreignKey:nodeID" json:"attrs"`
}

// TableName Node's table name
func (*Node) TableName() string {
	return TableNameNode
}
