// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNode = "nodes"

// Node mapped from table <nodes>
type Node struct {
	ID        int64        `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	GroupID   int64        `gorm:"column:groupID;type:int;not null" json:"groupID"`
	Name      string       `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Desc      string       `gorm:"column:desc;type:text" json:"desc"`
	Display   string       `gorm:"column:display;type:varchar(255);default:color" json:"display"`
	NodeAttrs []*NodesAttr `gorm:"foreignKey:nodeID" json:"node_attrs"`
}

// TableName Node's table name
func (*Node) TableName() string {
	return TableNameNode
}
