// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package service

object AlgoProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      service.Empty,
      service.Element,
      service.CreateAlgoReq,
      service.DropAlgoReq,
      service.AlgoReply,
      service.Algo,
      service.Rank,
      service.RankReply,
      service.Cluster,
      service.ClusterReply,
      service.MetricsReply,
      service.BaseReq,
      service.ShortestPathReq,
      service.CustomAlgoReq,
      service.CustomAlgoReply
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgphbGdvLnByb3RvEghzZXJ2aWNlcyIHCgVFbXB0eSL0AQoHRWxlbWVudBIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSN
  QoEdHlwZRgCIAEoDjIWLnNlcnZpY2VzLkVsZW1lbnQuVHlwZUIJ4j8GEgR0eXBlUgR0eXBlIpUBCgRUeXBlEhUKBUlOVDY0EAAaC
  uI/BxIFSU5UNjQSFwoGRE9VQkxFEAEaC+I/CBIGRE9VQkxFEhcKBlNUUklORxACGgviPwgSBlNUUklORxIhCgtMSVNUX0RPVUJMR
  RADGhDiPw0SC0xJU1RfRE9VQkxFEiEKC0xJU1RfU1RSSU5HEAQaEOI/DRILTElTVF9TVFJJTkciigIKDUNyZWF0ZUFsZ29SZXESH
  QoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEh0KBGRlc2MYAiABKAlCCeI/BhIEZGVzY1IEZGVzYxI2CgZwYXJhbXMYAyADK
  AsyES5zZXJ2aWNlcy5FbGVtZW50QgviPwgSBnBhcmFtc1IGcGFyYW1zEjAKBHJldHMYBCADKAsyES5zZXJ2aWNlcy5FbGVtZW50Q
  gniPwYSBHJldHNSBHJldHMSHQoEY29kZRgFIAEoCUIJ4j8GEgRjb2RlUgRjb2RlEjIKBHR5cGUYBiABKA4yEy5zZXJ2aWNlcy5Bb
  GdvLlR5cGVCCeI/BhIEdHlwZVIEdHlwZSIsCgtEcm9wQWxnb1JlcRIdCgRuYW1lGAEgASgJQgniPwYSBG5hbWVSBG5hbWUiPQoJQ
  Wxnb1JlcGx5EjAKBWFsZ29zGAEgAygLMg4uc2VydmljZXMuQWxnb0IK4j8HEgVhbGdvc1IFYWxnb3MiqAIKBEFsZ28SFwoCaWQYA
  SABKANCB+I/BBICaWRSAmlkEh0KBG5hbWUYAiABKAlCCeI/BhIEbmFtZVIEbmFtZRIdCgRkZXNjGAMgASgJQgniPwYSBGRlc2NSB
  GRlc2MSKQoIaXNDdXN0b20YBCABKAhCDeI/ChIIaXNDdXN0b21SCGlzQ3VzdG9tEjIKBHR5cGUYBSABKA4yEy5zZXJ2aWNlcy5Bb
  GdvLlR5cGVCCeI/BhIEdHlwZVIEdHlwZSJqCgRUeXBlEhMKBFJhbmsQABoJ4j8GEgRSYW5rEhkKB0NsdXN0ZXIQARoM4j8JEgdDb
  HVzdGVyEhkKB01ldHJpY3MQAhoM4j8JEgdNZXRyaWNzEhcKBk90aGVycxADGgviPwgSBk90aGVycyJHCgRSYW5rEh0KBG5hbWUYA
  SABKAlCCeI/BhIEbmFtZVIEbmFtZRIgCgVzY29yZRgCIAEoAUIK4j8HEgVzY29yZVIFc2NvcmUiPQoJUmFua1JlcGx5EjAKBXJhb
  mtzGAEgAygLMg4uc2VydmljZXMuUmFua0IK4j8HEgVyYW5rc1IFcmFua3MiSgoHQ2x1c3RlchIdCgRuYW1lGAEgASgJQgniPwYSB
  G5hbWVSBG5hbWUSIAoFbm9kZXMYAiADKAlCCuI/BxIFbm9kZXNSBW5vZGVzIkwKDENsdXN0ZXJSZXBseRI8CghjbHVzdGVycxgBI
  AMoCzIRLnNlcnZpY2VzLkNsdXN0ZXJCDeI/ChIIY2x1c3RlcnNSCGNsdXN0ZXJzIjAKDE1ldHJpY3NSZXBseRIgCgVzY29yZRgBI
  AEoAUIK4j8HEgVzY29yZVIFc2NvcmUiWQoHQmFzZVJlcRIgCgVncmFwaBgBIAEoCUIK4j8HEgVncmFwaFIFZ3JhcGgSLAoJZXhwb
  3J0S2V5GAIgASgJQg7iPwsSCWV4cG9ydEtleVIJZXhwb3J0S2V5InsKD1Nob3J0ZXN0UGF0aFJlcRIwCgRiYXNlGAEgASgLMhEuc
  2VydmljZXMuQmFzZVJlcUIJ4j8GEgRiYXNlUgRiYXNlEhoKA3NyYxgCIAEoCUII4j8FEgNzcmNSA3NyYxIaCgNkc3QYAyABKAlCC
  OI/BRIDZHN0UgNkc3QiZgoNQ3VzdG9tQWxnb1JlcRIwCgRiYXNlGAEgASgLMhEuc2VydmljZXMuQmFzZVJlcUIJ4j8GEgRiYXNlU
  gRiYXNlEiMKBnBhcmFtcxgCIAEoCUIL4j8IEgZwYXJhbXNSBnBhcmFtcyIwCg9DdXN0b21BbGdvUmVwbHkSHQoEcmV0cxgBIAEoC
  UIJ4j8GEgRyZXRzUgRyZXRzMsQECgRhbGdvEjoKCmNyZWF0ZUFsZ28SFy5zZXJ2aWNlcy5DcmVhdGVBbGdvUmVxGhMuc2VydmljZ
  XMuQWxnb1JlcGx5EjEKCXF1ZXJ5QWxnbxIPLnNlcnZpY2VzLkVtcHR5GhMuc2VydmljZXMuQWxnb1JlcGx5EjYKCGRyb3BBbGdvE
  hUuc2VydmljZXMuRHJvcEFsZ29SZXEaEy5zZXJ2aWNlcy5BbGdvUmVwbHkSMAoGZGVncmVlEhEuc2VydmljZXMuQmFzZVJlcRoTL
  nNlcnZpY2VzLlJhbmtSZXBseRIyCghwYWdlcmFuaxIRLnNlcnZpY2VzLkJhc2VSZXEaEy5zZXJ2aWNlcy5SYW5rUmVwbHkSNAoHb
  G91dmFpbhIRLnNlcnZpY2VzLkJhc2VSZXEaFi5zZXJ2aWNlcy5DbHVzdGVyUmVwbHkSQQoMc2hvcnRlc3RQYXRoEhkuc2VydmljZ
  XMuU2hvcnRlc3RQYXRoUmVxGhYuc2VydmljZXMuQ2x1c3RlclJlcGx5EjwKD2F2Z1Nob3J0ZXN0UGF0aBIRLnNlcnZpY2VzLkJhc
  2VSZXEaFi5zZXJ2aWNlcy5NZXRyaWNzUmVwbHkSOgoNYXZnQ2x1c3RlcmluZxIRLnNlcnZpY2VzLkJhc2VSZXEaFi5zZXJ2aWNlc
  y5NZXRyaWNzUmVwbHkSPAoGY3VzdG9tEhcuc2VydmljZXMuQ3VzdG9tQWxnb1JlcRoZLnNlcnZpY2VzLkN1c3RvbUFsZ29SZXBse
  WIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}