
// Generated by Akka gRPC. DO NOT EDIT.
package service

import scala.concurrent.ExecutionContext

import akka.actor.ClassicActorSystemProvider

import akka.grpc.GrpcChannel
import akka.grpc.GrpcClientCloseException
import akka.grpc.GrpcClientSettings

import akka.grpc.scaladsl.AkkaGrpcClient

import akka.grpc.internal.NettyClientUtils

import akka.grpc.AkkaGrpcGenerated

import akka.grpc.scaladsl.SingleResponseRequestBuilder
import akka.grpc.internal.ScalaUnaryRequestBuilder

// Not sealed so users can extend to write their stubs
@AkkaGrpcGenerated
trait algoClient extends algo with algoClientPowerApi with AkkaGrpcClient

@AkkaGrpcGenerated
object algoClient {
  def apply(settings: GrpcClientSettings)(implicit sys: ClassicActorSystemProvider): algoClient =
    new DefaultalgoClient(GrpcChannel(settings), isChannelOwned = true)
  def apply(channel: GrpcChannel)(implicit sys: ClassicActorSystemProvider): algoClient =
    new DefaultalgoClient(channel, isChannelOwned = false)

  private class DefaultalgoClient(channel: GrpcChannel, isChannelOwned: Boolean)(implicit sys: ClassicActorSystemProvider) extends algoClient {
    import algo.MethodDescriptors._

    private implicit val ex: ExecutionContext = sys.classicSystem.dispatcher
    private val settings = channel.settings
    private val options = NettyClientUtils.callOptions(settings)

    
    private def createAlgoRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(createAlgoDescriptor, channel, options, settings)
    
    
    private def queryAlgoRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(queryAlgoDescriptor, channel, options, settings)
    
    
    private def dropAlgoRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(dropAlgoDescriptor, channel, options, settings)
    
    
    private def degreeRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(degreeDescriptor, channel, options, settings)
    
    
    private def pagerankRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(pagerankDescriptor, channel, options, settings)
    
    
    private def louvainRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(louvainDescriptor, channel, options, settings)
    
    
    private def shortestPathRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(shortestPathDescriptor, channel, options, settings)
    
    
    private def avgShortestPathRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(avgShortestPathDescriptor, channel, options, settings)
    
    
    private def avgClusteringRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(avgClusteringDescriptor, channel, options, settings)
    
    
    private def customRequestBuilder(channel: akka.grpc.internal.InternalChannel) =
    
      new ScalaUnaryRequestBuilder(customDescriptor, channel, options, settings)
    
    

    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer createAlgo(services.CreateAlgoReq) if possible.
     */
    
    override def createAlgo(): SingleResponseRequestBuilder[service.CreateAlgoReq, service.AlgoReply] =
      createAlgoRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of createAlgo
     */
    def createAlgo(in: service.CreateAlgoReq): scala.concurrent.Future[service.AlgoReply] =
      createAlgo().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer queryAlgo(services.Empty) if possible.
     */
    
    override def queryAlgo(): SingleResponseRequestBuilder[service.Empty, service.AlgoReply] =
      queryAlgoRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of queryAlgo
     */
    def queryAlgo(in: service.Empty): scala.concurrent.Future[service.AlgoReply] =
      queryAlgo().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer dropAlgo(services.DropAlgoReq) if possible.
     */
    
    override def dropAlgo(): SingleResponseRequestBuilder[service.DropAlgoReq, service.AlgoReply] =
      dropAlgoRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of dropAlgo
     */
    def dropAlgo(in: service.DropAlgoReq): scala.concurrent.Future[service.AlgoReply] =
      dropAlgo().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer degree(services.BaseReq) if possible.
     */
    
    override def degree(): SingleResponseRequestBuilder[service.BaseReq, service.RankReply] =
      degreeRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of degree
     */
    def degree(in: service.BaseReq): scala.concurrent.Future[service.RankReply] =
      degree().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer pagerank(services.BaseReq) if possible.
     */
    
    override def pagerank(): SingleResponseRequestBuilder[service.BaseReq, service.RankReply] =
      pagerankRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of pagerank
     */
    def pagerank(in: service.BaseReq): scala.concurrent.Future[service.RankReply] =
      pagerank().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer louvain(services.BaseReq) if possible.
     */
    
    override def louvain(): SingleResponseRequestBuilder[service.BaseReq, service.ClusterReply] =
      louvainRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of louvain
     */
    def louvain(in: service.BaseReq): scala.concurrent.Future[service.ClusterReply] =
      louvain().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer shortestPath(services.ShortestPathReq) if possible.
     */
    
    override def shortestPath(): SingleResponseRequestBuilder[service.ShortestPathReq, service.ClusterReply] =
      shortestPathRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of shortestPath
     */
    def shortestPath(in: service.ShortestPathReq): scala.concurrent.Future[service.ClusterReply] =
      shortestPath().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer avgShortestPath(services.BaseReq) if possible.
     */
    
    override def avgShortestPath(): SingleResponseRequestBuilder[service.BaseReq, service.MetricsReply] =
      avgShortestPathRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of avgShortestPath
     */
    def avgShortestPath(in: service.BaseReq): scala.concurrent.Future[service.MetricsReply] =
      avgShortestPath().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer avgClustering(services.BaseReq) if possible.
     */
    
    override def avgClustering(): SingleResponseRequestBuilder[service.BaseReq, service.MetricsReply] =
      avgClusteringRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of avgClustering
     */
    def avgClustering(in: service.BaseReq): scala.concurrent.Future[service.MetricsReply] =
      avgClustering().invoke(in)
    
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer custom(services.CustomAlgoReq) if possible.
     */
    
    override def custom(): SingleResponseRequestBuilder[service.CustomAlgoReq, service.CustomAlgoReply] =
      customRequestBuilder(channel.internalChannel)
    

    /**
     * For access to method metadata use the parameterless version of custom
     */
    def custom(in: service.CustomAlgoReq): scala.concurrent.Future[service.CustomAlgoReply] =
      custom().invoke(in)
    

    override def close(): scala.concurrent.Future[akka.Done] =
      if (isChannelOwned) channel.close()
      else throw new GrpcClientCloseException()

    override def closed: scala.concurrent.Future[akka.Done] = channel.closed()
  }
}

@AkkaGrpcGenerated
trait algoClientPowerApi {
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer createAlgo(services.CreateAlgoReq) if possible.
   */
  
  def createAlgo(): SingleResponseRequestBuilder[service.CreateAlgoReq, service.AlgoReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer queryAlgo(services.Empty) if possible.
   */
  
  def queryAlgo(): SingleResponseRequestBuilder[service.Empty, service.AlgoReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer dropAlgo(services.DropAlgoReq) if possible.
   */
  
  def dropAlgo(): SingleResponseRequestBuilder[service.DropAlgoReq, service.AlgoReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer degree(services.BaseReq) if possible.
   */
  
  def degree(): SingleResponseRequestBuilder[service.BaseReq, service.RankReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer pagerank(services.BaseReq) if possible.
   */
  
  def pagerank(): SingleResponseRequestBuilder[service.BaseReq, service.RankReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer louvain(services.BaseReq) if possible.
   */
  
  def louvain(): SingleResponseRequestBuilder[service.BaseReq, service.ClusterReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer shortestPath(services.ShortestPathReq) if possible.
   */
  
  def shortestPath(): SingleResponseRequestBuilder[service.ShortestPathReq, service.ClusterReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer avgShortestPath(services.BaseReq) if possible.
   */
  
  def avgShortestPath(): SingleResponseRequestBuilder[service.BaseReq, service.MetricsReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer avgClustering(services.BaseReq) if possible.
   */
  
  def avgClustering(): SingleResponseRequestBuilder[service.BaseReq, service.MetricsReply] = ???
  
  
  /**
   * Lower level "lifted" version of the method, giving access to request metadata etc.
   * prefer custom(services.CustomAlgoReq) if possible.
   */
  
  def custom(): SingleResponseRequestBuilder[service.CustomAlgoReq, service.CustomAlgoReply] = ???
  
  

}
