// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package service

@SerialVersionUID(0L)
final case class ClusterReply(
                               clusters: _root_.scala.Seq[service.Cluster] = _root_.scala.Seq.empty,
                               unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ClusterReply] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      clusters.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      clusters.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearClusters = copy(clusters = _root_.scala.Seq.empty)
    def addClusters(__vs: service.Cluster *): ClusterReply = addAllClusters(__vs)
    def addAllClusters(__vs: Iterable[service.Cluster]): ClusterReply = copy(clusters = clusters ++ __vs)
    def withClusters(__v: _root_.scala.Seq[service.Cluster]): ClusterReply = copy(clusters = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => clusters
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(clusters.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: service.ClusterReply.type = service.ClusterReply
    // @@protoc_insertion_point(GeneratedMessage[services.ClusterReply])
}

object ClusterReply extends scalapb.GeneratedMessageCompanion[service.ClusterReply] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[service.ClusterReply] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): service.ClusterReply = {
    val __clusters: _root_.scala.collection.immutable.VectorBuilder[service.Cluster] = new _root_.scala.collection.immutable.VectorBuilder[service.Cluster]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __clusters += _root_.scalapb.LiteParser.readMessage[service.Cluster](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    service.ClusterReply(
        clusters = __clusters.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[service.ClusterReply] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      service.ClusterReply(
        clusters = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[service.Cluster]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AlgoProto.javaDescriptor.getMessageTypes().get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AlgoProto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = service.Cluster
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = service.ClusterReply(
    clusters = _root_.scala.Seq.empty
  )
  implicit class ClusterReplyLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, service.ClusterReply]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, service.ClusterReply](_l) {
    def clusters: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[service.Cluster]] = field(_.clusters)((c_, f_) => c_.copy(clusters = f_))
  }
  final val CLUSTERS_FIELD_NUMBER = 1
  def of(
    clusters: _root_.scala.Seq[service.Cluster]
  ): _root_.service.ClusterReply = _root_.service.ClusterReply(
    clusters
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[services.ClusterReply])
}
