// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package service

@SerialVersionUID(0L)
final case class CustomAlgoReq(
                                base: _root_.scala.Option[service.BaseReq] = _root_.scala.None,
                                params: _root_.scala.Predef.String = "",
                                unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[CustomAlgoReq] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (base.isDefined) {
        val __value = base.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = params
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      base.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = params
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def getBase: service.BaseReq = base.getOrElse(service.BaseReq.defaultInstance)
    def clearBase: CustomAlgoReq = copy(base = _root_.scala.None)
    def withBase(__v: service.BaseReq): CustomAlgoReq = copy(base = Option(__v))
    def withParams(__v: _root_.scala.Predef.String): CustomAlgoReq = copy(params = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => base.orNull
        case 2 => {
          val __t = params
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => base.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PString(params)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: service.CustomAlgoReq.type = service.CustomAlgoReq
    // @@protoc_insertion_point(GeneratedMessage[services.CustomAlgoReq])
}

object CustomAlgoReq extends scalapb.GeneratedMessageCompanion[service.CustomAlgoReq] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[service.CustomAlgoReq] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): service.CustomAlgoReq = {
    var __base: _root_.scala.Option[service.BaseReq] = _root_.scala.None
    var __params: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __base = Option(__base.fold(_root_.scalapb.LiteParser.readMessage[service.BaseReq](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __params = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    service.CustomAlgoReq(
        base = __base,
        params = __params,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[service.CustomAlgoReq] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      service.CustomAlgoReq(
        base = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[service.BaseReq]]),
        params = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AlgoProto.javaDescriptor.getMessageTypes().get(13)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AlgoProto.scalaDescriptor.messages(13)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = service.BaseReq
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = service.CustomAlgoReq(
    base = _root_.scala.None,
    params = ""
  )
  implicit class CustomAlgoReqLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, service.CustomAlgoReq]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, service.CustomAlgoReq](_l) {
    def base: _root_.scalapb.lenses.Lens[UpperPB, service.BaseReq] = field(_.getBase)((c_, f_) => c_.copy(base = Option(f_)))
    def optionalBase: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[service.BaseReq]] = field(_.base)((c_, f_) => c_.copy(base = f_))
    def params: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.params)((c_, f_) => c_.copy(params = f_))
  }
  final val BASE_FIELD_NUMBER = 1
  final val PARAMS_FIELD_NUMBER = 2
  def of(
          base: _root_.scala.Option[service.BaseReq],
          params: _root_.scala.Predef.String
  ): _root_.service.CustomAlgoReq = _root_.service.CustomAlgoReq(
    base,
    params
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[services.CustomAlgoReq])
}
