name: Push Image

on:
  push:
    branches: [ 'extends' ]
    paths-ignore:
      - 'example'
      - 'client'
      - 'README.md'
  pull_request:
    branches: [ 'extends' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out thr repo
        uses: actions/checkout@v3
      - name: Set Environment -- Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Set Environment -- Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Set Environment -- Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image -- graph
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: dockerfiles/graph.Dockerfile
          tags: applerodite/chs-graph:latest
      - name: Build and push Docker image -- sca
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: dockerfiles/sca.Dockerfile
          tags: applerodite/chs-sca:latest
      - name: Build and push Docker image -- task
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: dockerfiles/task.Dockerfile
          tags: applerodite/chs-task:latest
      - name: Build and push Docker image -- front
        uses: docker/build-push-action@v4
        with:
          context: front/
          push: true
          file: front/front.Dockerfile
          tags: applerodite/chs-front:latest
